fake_interpolating_controller_rate: 100
controller_list:
  - name: fake_piper_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - joint7
initial:  # Define initial robot poses per group
  - group: piper
    pose: zero
  - group: gripper
    pose: gripper_open